app = "project-hidden-feather"
primary_region = "fra"
kill_signal = "SIGTERM"

[env]
PORT = "8080"
DATABASE_PATH = "/app/data/project.db"
PHX_HOST = "project-hidden-feather.fly.dev"

[[mounts]]
source = "project"
destination = "/app/data"
auto_extend_size_threshold = 80
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 1000

[[vm]]
cpus = 1
memory = "1gb"
cpu_kind = "shared"
